import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const proximaNova = localFont({
  src: [
    { path: "../public/fonts/Fontspring-DEMO-proximanova-light.otf", weight: "300", style: "normal" },
    { path: "../public/fonts/Fontspring-DEMO-proximanova-regular.otf", weight: "400", style: "normal" },
    { path: "../public/fonts/Fontspring-DEMO-proximanova-medium.otf", weight: "500", style: "normal" },
    { path: "../public/fonts/Fontspring-DEMO-proximanova-semibold.otf", weight: "600", style: "normal" },
    { path: "../public/fonts/Fontspring-DEMO-proximanova-bold.otf", weight: "700", style: "normal" },
    { path: "../public/fonts/Fontspring-DEMO-proximanova-extrabold.otf", weight: "800", style: "normal" },
    { path: "../public/fonts/Fontspring-DEMO-proximanova-black.otf", weight: "900", style: "normal" },
  ],
  variable: "--font-proxima",
});


export const metadata: Metadata = {
  title: "Lumina",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={`${proximaNova.variable} antialiased`}
        cz-shortcut-listen="true"
      >
        {children}
      </body>
    </html>
  );
}
